import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import "./globals.css";

import MaterialUiSetup from "./styles";
import NavBar from "./nav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-neutral-900">
        <MaterialUiSetup>
          <div className="min-h-screen flex">
            <NavBar />
            <div className="flex flex-1 p-8 pl-[272px]">{children}</div>
          </div>
        </MaterialUiSetup>
      </body>
    </html>
  );
}
